import pygame

# GAME
NUM_ROWS = 3
NUM_COLUMNS = 3
EMPTY = 0
PLAYER1 = 1 # X
PLAYER2 = 2 # O

REWARD_WIN = 10
REWARD_LOST = -REWARD_WIN
REWARD_TIE = 2

# SIZES
PART_SIZE = 100
PART_MARGIN = 15
STICK_WIDTH = 20
MARGIN = 30
PLUS = 50   # Space added to the top margin

SCREEN_WIDTH = 2*MARGIN + NUM_COLUMNS*(PART_SIZE + 2*PART_MARGIN + STICK_WIDTH) - STICK_WIDTH
SCREEN_HEIGHT = PLUS + 2*MARGIN + NUM_ROWS*(PART_SIZE + 2*PART_MARGIN + STICK_WIDTH) - STICK_WIDTH


SIZE_FONT_BIG = 40

# COLORS
COLOR_TEXT = "#b68f40"
COLOR_BUTTON = "#d7fcd4"
WHITE = (255,255,255)
COLOR_O = "#d9efdb"
COLOR_X = "#bc1210"
COLOR_STICK = "#facd75"

# CONSTANTS
TITLE = 'TIC TAC TOE'
PLAY = 'PLAY'
Q_LEARNINNG = 'QLEARNING'
QUIT = 'QUIT'
PLAY_AGAIN = 'PLAY AGAIN'
MAIN_MENU = 'MAIN MENU'
TIE = 'TIE'
TURN = 'TURN!!'


# FOLDERS
ASSETS = 'assets/'

IMAGE_LOGO = ASSETS + 'logo.png'
IMAGE_BACKGROUND = ASSETS + 'background.png'
IMAGE_PLAY_BUTTON = ASSETS + 'Play Rect.png'
IMAGE_OPTIONS_BUTTON = ASSETS + 'Options Rect.png'
IMAGE_QUIT_BUTTON = ASSETS + 'Quit Rect.png'

FONT_GAMES = ASSETS + 'games.ttf'

BACKGROUND = pygame.image.load(IMAGE_BACKGROUND)
BACKGROUND = pygame.transform.scale(BACKGROUND, (SCREEN_WIDTH, SCREEN_HEIGHT))

QTABLE_FILE = ASSETS + 'qtable.pickle'